// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using videoGameApi.Model.Database;

#nullable disable

namespace videoGameApi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20241226095731_Accesories2")]
    partial class Accesories2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("videoGameApi.Model.VideoGame", b =>
                {
                    b.Property<int>("VideoGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoGameId"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdVideoGameMercado")
                        .HasColumnType("int");

                    b.Property<int?>("IdVideoGameVersion")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VideGameThemeId")
                        .HasColumnType("int");

                    b.Property<int?>("VideoGameAccesoriesId")
                        .HasColumnType("int");

                    b.HasKey("VideoGameId");

                    b.HasIndex("VideoGameAccesoriesId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            VideoGameId = 1,
                            Developer = "9",
                            Platform = "OS",
                            Publisher = "Male",
                            Title = "new"
                        },
                        new
                        {
                            VideoGameId = 2,
                            Developer = "19",
                            Platform = "WIN",
                            Publisher = "Male",
                            Title = "old"
                        },
                        new
                        {
                            VideoGameId = 3,
                            Developer = "29",
                            Platform = "LIN",
                            Publisher = "Male",
                            Title = "teen"
                        },
                        new
                        {
                            VideoGameId = 4,
                            Developer = "88",
                            Platform = "APP",
                            Publisher = "Male",
                            Title = "child"
                        });
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameAccesories", b =>
                {
                    b.Property<int>("VideoGameAccesoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoGameAccesoriesId"));

                    b.Property<string>("VideoGameAccesoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGameAccesoryPrice")
                        .HasColumnType("int");

                    b.HasKey("VideoGameAccesoriesId");

                    b.ToTable("VideoGameAccesories");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RealeseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("VideoGameDetails");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameMercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreMercado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("VideoGameMercado");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameTheme", b =>
                {
                    b.Property<int>("VideoGameThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoGameThemeId"));

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.Property<string>("VideoGameThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoGameThemeId");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("VideoGameTheme");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoGameId")
                        .IsUnique();

                    b.ToTable("VideoGameVersion");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGame", b =>
                {
                    b.HasOne("videoGameApi.Model.VideoGameAccesories", "videoGameAccesories")
                        .WithMany()
                        .HasForeignKey("VideoGameAccesoriesId");

                    b.Navigation("videoGameAccesories");
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameDetails", b =>
                {
                    b.HasOne("videoGameApi.Model.VideoGame", null)
                        .WithOne("VideoGameDetails")
                        .HasForeignKey("videoGameApi.Model.VideoGameDetails", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameMercado", b =>
                {
                    b.HasOne("videoGameApi.Model.VideoGame", null)
                        .WithOne("Mercado")
                        .HasForeignKey("videoGameApi.Model.VideoGameMercado", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameTheme", b =>
                {
                    b.HasOne("videoGameApi.Model.VideoGame", null)
                        .WithOne("VideGameThemes")
                        .HasForeignKey("videoGameApi.Model.VideoGameTheme", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGameVersion", b =>
                {
                    b.HasOne("videoGameApi.Model.VideoGame", null)
                        .WithOne("VideoGameVersions")
                        .HasForeignKey("videoGameApi.Model.VideoGameVersion", "VideoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("videoGameApi.Model.VideoGame", b =>
                {
                    b.Navigation("Mercado");

                    b.Navigation("VideGameThemes");

                    b.Navigation("VideoGameDetails");

                    b.Navigation("VideoGameVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
